# Generated by Django 4.0.5 on 2022-07-04 08:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2022, 7, 4, 10, 11, 25, 992739))),
                ('paciente', models.CharField(max_length=50, verbose_name='Paciente')),
                ('idP', models.CharField(max_length=50, verbose_name='Paciente')),
                ('descripcion_corta', models.CharField(max_length=100, verbose_name='Paciente')),
                ('archivo', models.ImageField(upload_to='Ecos')),
                ('publico', models.BooleanField(verbose_name='Publico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recursos',
                'verbose_name_plural': 'Ecos',
                'ordering': ['id'],
            },
        ),
    ]
