# Generated by Django 4.0.5 on 2022-07-04 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariolog', '0002_alter_ecos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecos',
            name='descripcion_corta',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ecos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 10, 18, 33, 298234), editable=False),
        ),
        migrations.AlterField(
            model_name='ecos',
            name='idP',
            field=models.CharField(max_length=50, verbose_name='Id del paciente'),
        ),
    ]
