# Generated by Django 4.0.5 on 2022-07-04 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariolog', '0003_alter_ecos_descripcion_corta_alter_ecos_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 10, 33, 27, 407310), editable=False),
        ),
    ]
