# Generated by Django 4.0.5 on 2022-07-04 09:36

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariolog', '0004_alter_ecos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecos',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Descripion'),
        ),
        migrations.AlterField(
            model_name='ecos',
            name='descripcion_corta',
            field=models.CharField(max_length=100, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='ecos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 11, 36, 0, 371089), editable=False),
        ),
    ]
