# Generated by Django 4.0.5 on 2022-07-05 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariolog', '0005_ecos_descripcion_alter_ecos_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 10, 34, 55, 836053), editable=False),
        ),
    ]
