# Generated by Django 4.0.5 on 2022-07-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariolog', '0006_alter_ecos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
