# Generated by Django 4.0.5 on 2022-07-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariolog', '0007_alter_ecos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecos',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripion'),
        ),
        migrations.AlterField(
            model_name='ecos',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
