# Generated by Django 4.0.5 on 2022-07-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajesSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre Completo')),
                ('movil', models.PositiveIntegerField(verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('empresa', models.CharField(max_length=100, verbose_name='Organización')),
                ('cuerpo', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Solicitud de Aplicación',
                'verbose_name_plural': 'Solicitudes de Aplicacióna',
            },
        ),
    ]
