# Generated by Django 4.0.5 on 2022-07-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajessolicitud',
            options={'verbose_name': 'Solicitud de Aplicación', 'verbose_name_plural': 'Solicitudes de Aplicaciones'},
        ),
        migrations.AlterField(
            model_name='mensajessolicitud',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='mensajessolicitud',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organización'),
        ),
    ]
